spring:
  profiles:
    active: dev

# MyBatis-plus配置
mybatis-plus:
  # 配置Mapper映射文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置使用默认的IdWorker雪花算法生成id
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
    banner: false
  # 配置MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.ihrm.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

# MyBatis SQL 打印(方法接口所在的包,不是Mapper.xml所在的包)
logging:
  level:
    com.ihrm.company.dao: debug
